file_format: "1"
id: totemrollin
name: TOTEMROLLIN
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - totemrollin_left
  - totemrollin_right
